name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
    env:
      PATH: C:\cygwin\bin
    steps:
      - name: Install Cygwin Git
        uses: cygwin/cygwin-install-action@ad81540ad7c2726e17c08401fbeca6380cc7f463
        with:
          packages: git
        timeout-minutes: 10
      - name: Checkout
        uses: actions/checkout@v2
        timeout-minutes: 1
      - name: Load packages to install
        id: cyg-package-list
        run: |
          printf '::set-output name=packages::'
          tr '\n' ' ' <build-requires.txt
        timeout-minutes: 1
      - name: Install Cygwin build requirements
        uses: cygwin/cygwin-install-action@ad81540ad7c2726e17c08401fbeca6380cc7f463
        with:
          packages: ${{ steps.cyg-package-list.outputs.packages }}
        timeout-minutes: 30
      - name: Generate cygcheck output
        if: always()
        run: cygcheck -srv >/var/log/cygcheck.out
        timeout-minutes: 5
      - name: Store Cygwin logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cygwin-logs
          path: 'C:\cygwin\var\log\'
        timeout-minutes: 5
      - name: Cygport download
        run: cygport asciidoc.cygport download
        timeout-minutes: 5
      - name: Cygport prep
        run: cygport asciidoc.cygport prep
        timeout-minutes: 1
      - name: Cygport compile
        run: cygport asciidoc.cygport compile
        timeout-minutes: 5
      - name: Install pytest-mock
        run: python3 -m pip install pytest-mock
        timeout-minutes: 5
      - name: Cygport test
        run: cygport asciidoc.cygport test
        timeout-minutes: 5
      - name: Cygport install
        run: cygport asciidoc.cygport install
        timeout-minutes: 5
      - name: Cygport package
        run: cygport asciidoc.cygport package
        timeout-minutes: 5
      - name: Configure SSH
        if: github.ref == 'refs/heads/main'
        env:
          MAINTAINER_KEY: ${{ secrets.MAINTAINER_KEY }}
        run: |
          umask 0077
          mkdir -p ~/.ssh
          echo "$MAINTAINER_KEY" >~/.ssh/id_rsa
          echo 'cygwin.com,8.43.85.97 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGqrxexIuyqmCVe33p1HuhUFzsXte5QZKb+BJlsRrvXOpUOJEW2S0kszyAiymeV7AXaYmHDKVRJpGVR+0ua0Xww=' >~/.ssh/known_hosts
        timeout-minutes: 1
      - name: Cygport upload
        if: github.ref == 'refs/heads/main'
        run: SSH_KEY=~/.ssh/id_rsa cygport asciidoc.cygport stage
        timeout-minutes: 5
      - name: Mirror to Cygwin Git repositories
        if: github.ref == 'refs/heads/main'
        run: git push cygwin@cygwin.com:/git/cygwin-packages/asciidoc '${{ github.ref }}'
        timeout-minutes: 5
      - name: Tar up build results
        if: always()
        run: tar -caf asciidoc.txz asciidoc-*-*.*/
        timeout-minutes: 10
      - name: Store build results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: asciidoc.txz
          if-no-files-found: error
        timeout-minutes: 5
